"""Read-only V5 controlled-retraining readiness audit; never trains or writes production."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import pandas as pd
B=Path(__file__).resolve().parents[1];S=B/'stage7'
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for x in iter(lambda:f.read(1048576),b''):h.update(x)
 return h.hexdigest()
def main():
 prod=[B/'models/vae_model.pth',B/'models/deployment_config.json',B/'dataset/preprocessed/scaler.pkl',B/'dataset/preprocessed/label_encoders.pkl',B/'dataset/preprocessed/X_train.npy'];before={str(p.relative_to(B)):sha(p) for p in prod}
 v=pd.read_csv(S/'stage7_redesign_v5_raw.csv');raw=pd.read_csv(B/'dataset/retraining/retraining_dataset_combined_raw.csv',encoding='utf-8-sig');normal=raw[(raw.candidate_type=='NORMAL')&(raw.source_type=='SYNTHETIC')]
 expected={'suspicious_external_access':300,'offhours_sensitive_external_access':400,'credential_takeover_compound':300};actual=v.anomaly_type.value_counts().to_dict();source_overlap=set(v.base_record_id.astype(str)) & set(normal.source_id.astype(str))
 audit={'dataset_integrity':{'rows':len(v),'expected_counts':expected,'actual_counts':actual,'duplicate_source_records':int(v.base_record_id.duplicated().sum()),'duplicate_anomaly_records':int(v.duplicated().sum()),'hash':sha(S/'stage7_redesign_v5_raw.csv'),'metadata':json.loads((S/'stage7_v5_generation_metadata.json').read_text())},'training_separation':{'normal_available':len(normal),'v5_anomalies':len(v),'source_records_also_in_normal_pool':len(source_overlap),'status':'BLOCKED: source-aware split not yet materialized','required_protocol':'split normal sources first (seed 42); exclude every selected anomaly base_record_id from normal validation/test and preferably all training; fit candidate experiment encoders/scaler on train-normal only; attach V5 anomalies only to validation/test.'},'preprocessing':{'features':['user_id','activity','status','device','ip_address','duration_ms_log1p','object_count_log1p','hour_wib','day_of_week_wib'],'status':'COMPATIBLE with existing candidate contract; no artifact refit performed'},'taxonomy':{'kept':list(expected),'removed':['mass_archive_access'],'rejected':['scripted_rapid_failure_v5'],'note':'Removal/rejection is an observability/model-indistinguishability limitation, not denial of real-world threats.'},'decision':'CONTROLLED RETRAINING BLOCKED','blockers':['No source-aware normal/anomaly split artifact has been defined or materialized.','V5 anomaly base sources remain members of the available normal pool; using them in a normal evaluation path would cause source leakage.'],'production_before':before,'production_after':{str(p.relative_to(B)):sha(p) for p in prod},'candidate_hash':sha(B/'models/candidate/vae_model_candidate.pth'),'production_threshold':json.loads((B/'models/deployment_config.json').read_text())['threshold'],'retraining':'NOT PERFORMED','deployment':'NOT PERFORMED','production_modified':'NO','threshold_modified':'NO','service_restarted':'NO','stage8':'NOT STARTED'}
 (S/'stage7_v5_retraining_readiness.json').write_text(json.dumps(audit,indent=2));(S/'stage7_v5_production_hash_snapshot.json').write_text(json.dumps({'before':before,'after':audit['production_after'],'match':before==audit['production_after']},indent=2))
 proposal={'seed':42,'normal_source_split':'70% train-normal, 15% validation-normal, 15% test-normal after excluding all 1,000 V5 base_record_id sources from normal evaluation; document any reduction explicitly','anomaly_usage':'VAE fit: train-normal only. Validation/test: normal split plus V5 anomalies, source-disjoint from their normal counterparts.','scaler_encoder':'fit experiment-only artifacts on train-normal only; never overwrite candidate or production artifacts.'};(S/'stage7_v5_training_split_proposal.json').write_text(json.dumps(proposal,indent=2))
 rep='# V5 Controlled Retraining Readiness\n\n**CONTROLLED RETRAINING BLOCKED.** Dataset, preprocessing semantics, taxonomy, determinism, and production isolation are acceptable; the blocking issue is an unmaterialized source-aware split. All V5 base sources still exist in the normal pool, so leakage cannot be excluded until a protocol artifact explicitly assigns/excludes them.\n\n## Required authorization gate\nMaterialize an experiment-only split with seed 42; fit new experimental preprocessing strictly on train-normal; retain V5 anomalies for validation/test only; prove source-disjointness; then retraining may be separately authorized.\n\nRETRAINING: NOT PERFORMED\nDEPLOYMENT: NOT PERFORMED\nPRODUCTION MODIFIED: NO\nTHRESHOLD MODIFIED: NO\nSERVICE RESTARTED: NO\nSTAGE 8: NOT STARTED\n';(S/'stage7_v5_retraining_readiness_report.md').write_text(rep)
if __name__=='__main__':main()
